### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by artur9010** [raspberrypi/maynard#40] opened 2015-10-09 17:53 UTC
Project is dead?

**Comment by MrSchism** [comment] 2015-10-09 18:06
This is a duplicate of #38.  I'd say it's technically 'unmaintained' as opposed to dead.  There are two PRs waiting for the people who created them to update.  One needs to be made posix.

**Comment by fooishbar** [comment] 2015-10-09 20:14
Duplicate of #38.

**Closed** 2015-10-09 20:14 UTC
